# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _gen3d
else:
    import _gen3d

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _gen3d.delete_SwigPyIterator

    def value(self):
        return _gen3d.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _gen3d.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _gen3d.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _gen3d.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _gen3d.SwigPyIterator_equal(self, x)

    def copy(self):
        return _gen3d.SwigPyIterator_copy(self)

    def next(self):
        return _gen3d.SwigPyIterator_next(self)

    def __next__(self):
        return _gen3d.SwigPyIterator___next__(self)

    def previous(self):
        return _gen3d.SwigPyIterator_previous(self)

    def advance(self, n):
        return _gen3d.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _gen3d.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _gen3d.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _gen3d.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _gen3d.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _gen3d.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _gen3d.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _gen3d:
_gen3d.SwigPyIterator_swigregister(SwigPyIterator)

class CameraInfoVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gen3d.CameraInfoVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gen3d.CameraInfoVector___nonzero__(self)

    def __bool__(self):
        return _gen3d.CameraInfoVector___bool__(self)

    def __len__(self):
        return _gen3d.CameraInfoVector___len__(self)

    def __getslice__(self, i, j):
        return _gen3d.CameraInfoVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gen3d.CameraInfoVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gen3d.CameraInfoVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gen3d.CameraInfoVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gen3d.CameraInfoVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gen3d.CameraInfoVector___setitem__(self, *args)

    def pop(self):
        return _gen3d.CameraInfoVector_pop(self)

    def append(self, x):
        return _gen3d.CameraInfoVector_append(self, x)

    def empty(self):
        return _gen3d.CameraInfoVector_empty(self)

    def size(self):
        return _gen3d.CameraInfoVector_size(self)

    def swap(self, v):
        return _gen3d.CameraInfoVector_swap(self, v)

    def begin(self):
        return _gen3d.CameraInfoVector_begin(self)

    def end(self):
        return _gen3d.CameraInfoVector_end(self)

    def rbegin(self):
        return _gen3d.CameraInfoVector_rbegin(self)

    def rend(self):
        return _gen3d.CameraInfoVector_rend(self)

    def clear(self):
        return _gen3d.CameraInfoVector_clear(self)

    def get_allocator(self):
        return _gen3d.CameraInfoVector_get_allocator(self)

    def pop_back(self):
        return _gen3d.CameraInfoVector_pop_back(self)

    def erase(self, *args):
        return _gen3d.CameraInfoVector_erase(self, *args)

    def __init__(self, *args):
        _gen3d.CameraInfoVector_swiginit(self, _gen3d.new_CameraInfoVector(*args))

    def push_back(self, x):
        return _gen3d.CameraInfoVector_push_back(self, x)

    def front(self):
        return _gen3d.CameraInfoVector_front(self)

    def back(self):
        return _gen3d.CameraInfoVector_back(self)

    def assign(self, n, x):
        return _gen3d.CameraInfoVector_assign(self, n, x)

    def resize(self, *args):
        return _gen3d.CameraInfoVector_resize(self, *args)

    def insert(self, *args):
        return _gen3d.CameraInfoVector_insert(self, *args)

    def reserve(self, n):
        return _gen3d.CameraInfoVector_reserve(self, n)

    def capacity(self):
        return _gen3d.CameraInfoVector_capacity(self)
    __swig_destroy__ = _gen3d.delete_CameraInfoVector

# Register CameraInfoVector in _gen3d:
_gen3d.CameraInfoVector_swigregister(CameraInfoVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gen3d.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gen3d.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _gen3d.DoubleVector___bool__(self)

    def __len__(self):
        return _gen3d.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _gen3d.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gen3d.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gen3d.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gen3d.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gen3d.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gen3d.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _gen3d.DoubleVector_pop(self)

    def append(self, x):
        return _gen3d.DoubleVector_append(self, x)

    def empty(self):
        return _gen3d.DoubleVector_empty(self)

    def size(self):
        return _gen3d.DoubleVector_size(self)

    def swap(self, v):
        return _gen3d.DoubleVector_swap(self, v)

    def begin(self):
        return _gen3d.DoubleVector_begin(self)

    def end(self):
        return _gen3d.DoubleVector_end(self)

    def rbegin(self):
        return _gen3d.DoubleVector_rbegin(self)

    def rend(self):
        return _gen3d.DoubleVector_rend(self)

    def clear(self):
        return _gen3d.DoubleVector_clear(self)

    def get_allocator(self):
        return _gen3d.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _gen3d.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _gen3d.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _gen3d.DoubleVector_swiginit(self, _gen3d.new_DoubleVector(*args))

    def push_back(self, x):
        return _gen3d.DoubleVector_push_back(self, x)

    def front(self):
        return _gen3d.DoubleVector_front(self)

    def back(self):
        return _gen3d.DoubleVector_back(self)

    def assign(self, n, x):
        return _gen3d.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _gen3d.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _gen3d.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _gen3d.DoubleVector_reserve(self, n)

    def capacity(self):
        return _gen3d.DoubleVector_capacity(self)
    __swig_destroy__ = _gen3d.delete_DoubleVector

# Register DoubleVector in _gen3d:
_gen3d.DoubleVector_swigregister(DoubleVector)

class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gen3d.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gen3d.StringVector___nonzero__(self)

    def __bool__(self):
        return _gen3d.StringVector___bool__(self)

    def __len__(self):
        return _gen3d.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _gen3d.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gen3d.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gen3d.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gen3d.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gen3d.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gen3d.StringVector___setitem__(self, *args)

    def pop(self):
        return _gen3d.StringVector_pop(self)

    def append(self, x):
        return _gen3d.StringVector_append(self, x)

    def empty(self):
        return _gen3d.StringVector_empty(self)

    def size(self):
        return _gen3d.StringVector_size(self)

    def swap(self, v):
        return _gen3d.StringVector_swap(self, v)

    def begin(self):
        return _gen3d.StringVector_begin(self)

    def end(self):
        return _gen3d.StringVector_end(self)

    def rbegin(self):
        return _gen3d.StringVector_rbegin(self)

    def rend(self):
        return _gen3d.StringVector_rend(self)

    def clear(self):
        return _gen3d.StringVector_clear(self)

    def get_allocator(self):
        return _gen3d.StringVector_get_allocator(self)

    def pop_back(self):
        return _gen3d.StringVector_pop_back(self)

    def erase(self, *args):
        return _gen3d.StringVector_erase(self, *args)

    def __init__(self, *args):
        _gen3d.StringVector_swiginit(self, _gen3d.new_StringVector(*args))

    def push_back(self, x):
        return _gen3d.StringVector_push_back(self, x)

    def front(self):
        return _gen3d.StringVector_front(self)

    def back(self):
        return _gen3d.StringVector_back(self)

    def assign(self, n, x):
        return _gen3d.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _gen3d.StringVector_resize(self, *args)

    def insert(self, *args):
        return _gen3d.StringVector_insert(self, *args)

    def reserve(self, n):
        return _gen3d.StringVector_reserve(self, n)

    def capacity(self):
        return _gen3d.StringVector_capacity(self)
    __swig_destroy__ = _gen3d.delete_StringVector

# Register StringVector in _gen3d:
_gen3d.StringVector_swigregister(StringVector)

class Point3fVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gen3d.Point3fVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gen3d.Point3fVector___nonzero__(self)

    def __bool__(self):
        return _gen3d.Point3fVector___bool__(self)

    def __len__(self):
        return _gen3d.Point3fVector___len__(self)

    def __getslice__(self, i, j):
        return _gen3d.Point3fVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gen3d.Point3fVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gen3d.Point3fVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gen3d.Point3fVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gen3d.Point3fVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gen3d.Point3fVector___setitem__(self, *args)

    def pop(self):
        return _gen3d.Point3fVector_pop(self)

    def append(self, x):
        return _gen3d.Point3fVector_append(self, x)

    def empty(self):
        return _gen3d.Point3fVector_empty(self)

    def size(self):
        return _gen3d.Point3fVector_size(self)

    def swap(self, v):
        return _gen3d.Point3fVector_swap(self, v)

    def begin(self):
        return _gen3d.Point3fVector_begin(self)

    def end(self):
        return _gen3d.Point3fVector_end(self)

    def rbegin(self):
        return _gen3d.Point3fVector_rbegin(self)

    def rend(self):
        return _gen3d.Point3fVector_rend(self)

    def clear(self):
        return _gen3d.Point3fVector_clear(self)

    def get_allocator(self):
        return _gen3d.Point3fVector_get_allocator(self)

    def pop_back(self):
        return _gen3d.Point3fVector_pop_back(self)

    def erase(self, *args):
        return _gen3d.Point3fVector_erase(self, *args)

    def __init__(self, *args):
        _gen3d.Point3fVector_swiginit(self, _gen3d.new_Point3fVector(*args))

    def push_back(self, x):
        return _gen3d.Point3fVector_push_back(self, x)

    def front(self):
        return _gen3d.Point3fVector_front(self)

    def back(self):
        return _gen3d.Point3fVector_back(self)

    def assign(self, n, x):
        return _gen3d.Point3fVector_assign(self, n, x)

    def resize(self, *args):
        return _gen3d.Point3fVector_resize(self, *args)

    def insert(self, *args):
        return _gen3d.Point3fVector_insert(self, *args)

    def reserve(self, n):
        return _gen3d.Point3fVector_reserve(self, n)

    def capacity(self):
        return _gen3d.Point3fVector_capacity(self)
    __swig_destroy__ = _gen3d.delete_Point3fVector

# Register Point3fVector in _gen3d:
_gen3d.Point3fVector_swigregister(Point3fVector)

class Point2fVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gen3d.Point2fVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gen3d.Point2fVector___nonzero__(self)

    def __bool__(self):
        return _gen3d.Point2fVector___bool__(self)

    def __len__(self):
        return _gen3d.Point2fVector___len__(self)

    def __getslice__(self, i, j):
        return _gen3d.Point2fVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gen3d.Point2fVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gen3d.Point2fVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gen3d.Point2fVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gen3d.Point2fVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gen3d.Point2fVector___setitem__(self, *args)

    def pop(self):
        return _gen3d.Point2fVector_pop(self)

    def append(self, x):
        return _gen3d.Point2fVector_append(self, x)

    def empty(self):
        return _gen3d.Point2fVector_empty(self)

    def size(self):
        return _gen3d.Point2fVector_size(self)

    def swap(self, v):
        return _gen3d.Point2fVector_swap(self, v)

    def begin(self):
        return _gen3d.Point2fVector_begin(self)

    def end(self):
        return _gen3d.Point2fVector_end(self)

    def rbegin(self):
        return _gen3d.Point2fVector_rbegin(self)

    def rend(self):
        return _gen3d.Point2fVector_rend(self)

    def clear(self):
        return _gen3d.Point2fVector_clear(self)

    def get_allocator(self):
        return _gen3d.Point2fVector_get_allocator(self)

    def pop_back(self):
        return _gen3d.Point2fVector_pop_back(self)

    def erase(self, *args):
        return _gen3d.Point2fVector_erase(self, *args)

    def __init__(self, *args):
        _gen3d.Point2fVector_swiginit(self, _gen3d.new_Point2fVector(*args))

    def push_back(self, x):
        return _gen3d.Point2fVector_push_back(self, x)

    def front(self):
        return _gen3d.Point2fVector_front(self)

    def back(self):
        return _gen3d.Point2fVector_back(self)

    def assign(self, n, x):
        return _gen3d.Point2fVector_assign(self, n, x)

    def resize(self, *args):
        return _gen3d.Point2fVector_resize(self, *args)

    def insert(self, *args):
        return _gen3d.Point2fVector_insert(self, *args)

    def reserve(self, n):
        return _gen3d.Point2fVector_reserve(self, n)

    def capacity(self):
        return _gen3d.Point2fVector_capacity(self)
    __swig_destroy__ = _gen3d.delete_Point2fVector

# Register Point2fVector in _gen3d:
_gen3d.Point2fVector_swigregister(Point2fVector)

INFINITE = _gen3d.INFINITE
DEPTH_MAP_ALIGN_RGB = _gen3d.DEPTH_MAP_ALIGN_RGB
DEPTH_MAP_ALIGN_CAMERA = _gen3d.DEPTH_MAP_ALIGN_CAMERA
BINOCULAR_RECONSTRUCTION = _gen3d.BINOCULAR_RECONSTRUCTION
MONOCULAR_RECONSTRUCTION = _gen3d.MONOCULAR_RECONSTRUCTION
CamPro = _gen3d.CamPro
Camera_SoftTrigger = _gen3d.Camera_SoftTrigger
Camera_GPIOTrigger = _gen3d.Camera_GPIOTrigger
Camera_SoftSingleAsyncTrigger = _gen3d.Camera_SoftSingleAsyncTrigger
ParamType_Begin = _gen3d.ParamType_Begin
Capture_WorkMode = _gen3d.Capture_WorkMode
Capture_Delay = _gen3d.Capture_Delay
IR_Exposure = _gen3d.IR_Exposure
IR_Gain = _gen3d.IR_Gain
IR_LightSource = _gen3d.IR_LightSource
IR_HDRCnt = _gen3d.IR_HDRCnt
IR_HDRExposure2 = _gen3d.IR_HDRExposure2
IR_HDRExposure3 = _gen3d.IR_HDRExposure3
IR_PixelType = _gen3d.IR_PixelType
Rgb_BrightnessSet = _gen3d.Rgb_BrightnessSet
Rgb_Contrast = _gen3d.Rgb_Contrast
Rgb_Saturation = _gen3d.Rgb_Saturation
Rgb_Hue = _gen3d.Rgb_Hue
Rgb_Gamma = _gen3d.Rgb_Gamma
Rgb_WhiteBalanceTemperature = _gen3d.Rgb_WhiteBalanceTemperature
Rgb_Sharpness = _gen3d.Rgb_Sharpness
Rgb_BacklightCompensation = _gen3d.Rgb_BacklightCompensation
Rgb_ExposureAbsolute = _gen3d.Rgb_ExposureAbsolute
Rgb_WhiteBalanceTemperatureAuto = _gen3d.Rgb_WhiteBalanceTemperatureAuto
Rgb_ExposureAuto = _gen3d.Rgb_ExposureAuto
Mems_TriggerDelay = _gen3d.Mems_TriggerDelay
Mems_LaserKValue = _gen3d.Mems_LaserKValue
Algo_DepthMapType = _gen3d.Algo_DepthMapType
Algo_DilateKsize = _gen3d.Algo_DilateKsize
Algo_FillHole = _gen3d.Algo_FillHole
Algo_KSize = _gen3d.Algo_KSize
Algo_Sigma = _gen3d.Algo_Sigma
Algo_Smooth = _gen3d.Algo_Smooth
Algo_SmoothType = _gen3d.Algo_SmoothType
Algo_ZfRangeMax = _gen3d.Algo_ZfRangeMax
Algo_ZfRangeMin = _gen3d.Algo_ZfRangeMin
Algo_WrapphaseType = _gen3d.Algo_WrapphaseType
Algo_FilterType = _gen3d.Algo_FilterType
Algo_TriThreshold = _gen3d.Algo_TriThreshold
Algo_ShadowThreshold = _gen3d.Algo_ShadowThreshold
Algo_GradNeedSerialNum = _gen3d.Algo_GradNeedSerialNum
Algo_RecommendedZfRangeMax = _gen3d.Algo_RecommendedZfRangeMax
Algo_RecommendedZfRangeMin = _gen3d.Algo_RecommendedZfRangeMin
Algo_OutlierRemoval = _gen3d.Algo_OutlierRemoval
Algo_XfRangeMax = _gen3d.Algo_XfRangeMax
Algo_XfRangeMin = _gen3d.Algo_XfRangeMin
Algo_YfRangeMax = _gen3d.Algo_YfRangeMax
Algo_YfRangeMin = _gen3d.Algo_YfRangeMin
Algo_ImageFilterType = _gen3d.Algo_ImageFilterType
Algo_SmoothRadius = _gen3d.Algo_SmoothRadius
Algo_ZSigma = _gen3d.Algo_ZSigma
Algo_TextureMappingType = _gen3d.Algo_TextureMappingType
Algo_LrCheck = _gen3d.Algo_LrCheck
Algo_LrCheckThreshold = _gen3d.Algo_LrCheckThreshold
ParamType_End = _gen3d.ParamType_End
ParamType_Get_Offset = _gen3d.ParamType_Get_Offset
class FrameInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    frameIndex = property(_gen3d.FrameInfo_frameIndex_get, _gen3d.FrameInfo_frameIndex_set)
    frameTimestamp = property(_gen3d.FrameInfo_frameTimestamp_get, _gen3d.FrameInfo_frameTimestamp_set)
    frameTotalDuration = property(_gen3d.FrameInfo_frameTotalDuration_get, _gen3d.FrameInfo_frameTotalDuration_set)
    frameAcquisitionDuration = property(_gen3d.FrameInfo_frameAcquisitionDuration_get, _gen3d.FrameInfo_frameAcquisitionDuration_set)
    frameComputationDuration = property(_gen3d.FrameInfo_frameComputationDuration_get, _gen3d.FrameInfo_frameComputationDuration_set)
    frameTransferDuration = property(_gen3d.FrameInfo_frameTransferDuration_get, _gen3d.FrameInfo_frameTransferDuration_set)

    def __init__(self):
        _gen3d.FrameInfo_swiginit(self, _gen3d.new_FrameInfo())
    __swig_destroy__ = _gen3d.delete_FrameInfo

# Register FrameInfo in _gen3d:
_gen3d.FrameInfo_swigregister(FrameInfo)

class FrameData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _gen3d.delete_FrameData

    def __init__(self, *args):
        _gen3d.FrameData_swiginit(self, _gen3d.new_FrameData(*args))
    frameInfo = property(_gen3d.FrameData_frameInfo_get, _gen3d.FrameData_frameInfo_set)
    point3D = property(_gen3d.FrameData_point3D_get, _gen3d.FrameData_point3D_set)
    pointUV = property(_gen3d.FrameData_pointUV_get, _gen3d.FrameData_pointUV_set)
    triangleIndices = property(_gen3d.FrameData_triangleIndices_get, _gen3d.FrameData_triangleIndices_set)
    depthmap = property(_gen3d.FrameData_depthmap_get, _gen3d.FrameData_depthmap_set)
    normals = property(_gen3d.FrameData_normals_get, _gen3d.FrameData_normals_set)
    pointColor = property(_gen3d.FrameData_pointColor_get, _gen3d.FrameData_pointColor_set)
    texture = property(_gen3d.FrameData_texture_get, _gen3d.FrameData_texture_set)
    remapTexture = property(_gen3d.FrameData_remapTexture_get, _gen3d.FrameData_remapTexture_set)
    point3DSize = property(_gen3d.FrameData_point3DSize_get, _gen3d.FrameData_point3DSize_set)
    pointUVSize = property(_gen3d.FrameData_pointUVSize_get, _gen3d.FrameData_pointUVSize_set)
    triangleIndicesSize = property(_gen3d.FrameData_triangleIndicesSize_get, _gen3d.FrameData_triangleIndicesSize_set)
    depthmapSize = property(_gen3d.FrameData_depthmapSize_get, _gen3d.FrameData_depthmapSize_set)
    normalsSize = property(_gen3d.FrameData_normalsSize_get, _gen3d.FrameData_normalsSize_set)
    pointColorSize = property(_gen3d.FrameData_pointColorSize_get, _gen3d.FrameData_pointColorSize_set)
    textureSize = property(_gen3d.FrameData_textureSize_get, _gen3d.FrameData_textureSize_set)
    pointCount = property(_gen3d.FrameData_pointCount_get, _gen3d.FrameData_pointCount_set)
    remapTextureSize = property(_gen3d.FrameData_remapTextureSize_get, _gen3d.FrameData_remapTextureSize_set)

# Register FrameData in _gen3d:
_gen3d.FrameData_swigregister(FrameData)

class OutputSettings(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sendPoint3D = property(_gen3d.OutputSettings_sendPoint3D_get, _gen3d.OutputSettings_sendPoint3D_set)
    sendPointUV = property(_gen3d.OutputSettings_sendPointUV_get, _gen3d.OutputSettings_sendPointUV_set)
    sendTriangleIndices = property(_gen3d.OutputSettings_sendTriangleIndices_get, _gen3d.OutputSettings_sendTriangleIndices_set)
    sendDepthmap = property(_gen3d.OutputSettings_sendDepthmap_get, _gen3d.OutputSettings_sendDepthmap_set)
    sendNormals = property(_gen3d.OutputSettings_sendNormals_get, _gen3d.OutputSettings_sendNormals_set)
    sendPointColor = property(_gen3d.OutputSettings_sendPointColor_get, _gen3d.OutputSettings_sendPointColor_set)
    sendTexture = property(_gen3d.OutputSettings_sendTexture_get, _gen3d.OutputSettings_sendTexture_set)
    sendRemapTexture = property(_gen3d.OutputSettings_sendRemapTexture_get, _gen3d.OutputSettings_sendRemapTexture_set)

    def __init__(self):
        _gen3d.OutputSettings_swiginit(self, _gen3d.new_OutputSettings())
    __swig_destroy__ = _gen3d.delete_OutputSettings

# Register OutputSettings in _gen3d:
_gen3d.OutputSettings_swigregister(OutputSettings)

class CameraParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    textureWidth = property(_gen3d.CameraParam_textureWidth_get, _gen3d.CameraParam_textureWidth_set)
    textureHeight = property(_gen3d.CameraParam_textureHeight_get, _gen3d.CameraParam_textureHeight_set)
    irWidth = property(_gen3d.CameraParam_irWidth_get, _gen3d.CameraParam_irWidth_set)
    irHeight = property(_gen3d.CameraParam_irHeight_get, _gen3d.CameraParam_irHeight_set)
    monoWidth = property(_gen3d.CameraParam_monoWidth_get, _gen3d.CameraParam_monoWidth_set)
    monoHeight = property(_gen3d.CameraParam_monoHeight_get, _gen3d.CameraParam_monoHeight_set)
    irPerNum = property(_gen3d.CameraParam_irPerNum_get, _gen3d.CameraParam_irPerNum_set)
    hdrCnt = property(_gen3d.CameraParam_hdrCnt_get, _gen3d.CameraParam_hdrCnt_set)
    pixelBytes = property(_gen3d.CameraParam_pixelBytes_get, _gen3d.CameraParam_pixelBytes_set)
    depthType = property(_gen3d.CameraParam_depthType_get, _gen3d.CameraParam_depthType_set)
    reconstructionType = property(_gen3d.CameraParam_reconstructionType_get, _gen3d.CameraParam_reconstructionType_set)

    def __init__(self):
        _gen3d.CameraParam_swiginit(self, _gen3d.new_CameraParam())
    __swig_destroy__ = _gen3d.delete_CameraParam

# Register CameraParam in _gen3d:
_gen3d.CameraParam_swigregister(CameraParam)

class CameraInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    errorCode = property(_gen3d.CameraInfo_errorCode_get, _gen3d.CameraInfo_errorCode_set)
    cameraName = property(_gen3d.CameraInfo_cameraName_get, _gen3d.CameraInfo_cameraName_set)
    model = property(_gen3d.CameraInfo_model_get, _gen3d.CameraInfo_model_set)
    cameraModel = property(_gen3d.CameraInfo_cameraModel_get, _gen3d.CameraInfo_cameraModel_set)
    cameraIP = property(_gen3d.CameraInfo_cameraIP_get, _gen3d.CameraInfo_cameraIP_set)
    port = property(_gen3d.CameraInfo_port_get, _gen3d.CameraInfo_port_set)
    userIP = property(_gen3d.CameraInfo_userIP_get, _gen3d.CameraInfo_userIP_set)
    serialNum = property(_gen3d.CameraInfo_serialNum_get, _gen3d.CameraInfo_serialNum_set)
    macAddr = property(_gen3d.CameraInfo_macAddr_get, _gen3d.CameraInfo_macAddr_set)
    cameraSystemVersion = property(_gen3d.CameraInfo_cameraSystemVersion_get, _gen3d.CameraInfo_cameraSystemVersion_set)
    algorithmVersion = property(_gen3d.CameraInfo_algorithmVersion_get, _gen3d.CameraInfo_algorithmVersion_set)
    memsVersion = property(_gen3d.CameraInfo_memsVersion_get, _gen3d.CameraInfo_memsVersion_set)
    cameraOSVersion = property(_gen3d.CameraInfo_cameraOSVersion_get, _gen3d.CameraInfo_cameraOSVersion_set)
    sdkVersion = property(_gen3d.CameraInfo_sdkVersion_get, _gen3d.CameraInfo_sdkVersion_set)
    rgbStatus = property(_gen3d.CameraInfo_rgbStatus_get, _gen3d.CameraInfo_rgbStatus_set)
    memsStatus = property(_gen3d.CameraInfo_memsStatus_get, _gen3d.CameraInfo_memsStatus_set)
    isDHCP = property(_gen3d.CameraInfo_isDHCP_get, _gen3d.CameraInfo_isDHCP_set)
    moduleID = property(_gen3d.CameraInfo_moduleID_get, _gen3d.CameraInfo_moduleID_set)
    algoType = property(_gen3d.CameraInfo_algoType_get, _gen3d.CameraInfo_algoType_set)
    camParam = property(_gen3d.CameraInfo_camParam_get, _gen3d.CameraInfo_camParam_set)
    outputSettings = property(_gen3d.CameraInfo_outputSettings_get, _gen3d.CameraInfo_outputSettings_set)

    def __init__(self):
        _gen3d.CameraInfo_swiginit(self, _gen3d.new_CameraInfo())
    __swig_destroy__ = _gen3d.delete_CameraInfo

# Register CameraInfo in _gen3d:
_gen3d.CameraInfo_swigregister(CameraInfo)

class ErrorCodeHandler(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _gen3d.delete_ErrorCodeHandler

    def Handle(self, errorCode):
        return _gen3d.ErrorCodeHandler_Handle(self, errorCode)

    def __init__(self):
        if self.__class__ == ErrorCodeHandler:
            _self = None
        else:
            _self = self
        _gen3d.ErrorCodeHandler_swiginit(self, _gen3d.new_ErrorCodeHandler(_self, ))
    def __disown__(self):
        self.this.disown()
        _gen3d.disown_ErrorCodeHandler(self)
        return weakref.proxy(self)

# Register ErrorCodeHandler in _gen3d:
_gen3d.ErrorCodeHandler_swigregister(ErrorCodeHandler)

class FrameDataHandler(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _gen3d.delete_FrameDataHandler

    def Handle(self, cameraInfo, frameData):
        return _gen3d.FrameDataHandler_Handle(self, cameraInfo, frameData)

    def __init__(self):
        if self.__class__ == FrameDataHandler:
            _self = None
        else:
            _self = self
        _gen3d.FrameDataHandler_swiginit(self, _gen3d.new_FrameDataHandler(_self, ))
    def __disown__(self):
        self.this.disown()
        _gen3d.disown_FrameDataHandler(self)
        return weakref.proxy(self)

# Register FrameDataHandler in _gen3d:
_gen3d.FrameDataHandler_swigregister(FrameDataHandler)

class Point3f(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_gen3d.Point3f_x_get, _gen3d.Point3f_x_set)
    y = property(_gen3d.Point3f_y_get, _gen3d.Point3f_y_set)
    z = property(_gen3d.Point3f_z_get, _gen3d.Point3f_z_set)

    def __init__(self):
        _gen3d.Point3f_swiginit(self, _gen3d.new_Point3f())
    __swig_destroy__ = _gen3d.delete_Point3f

# Register Point3f in _gen3d:
_gen3d.Point3f_swigregister(Point3f)

class Point2f(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_gen3d.Point2f_x_get, _gen3d.Point2f_x_set)
    y = property(_gen3d.Point2f_y_get, _gen3d.Point2f_y_set)

    def __init__(self):
        _gen3d.Point2f_swiginit(self, _gen3d.new_Point2f())
    __swig_destroy__ = _gen3d.delete_Point2f

# Register Point2f in _gen3d:
_gen3d.Point2f_swigregister(Point2f)

CAM_LEFT = _gen3d.CAM_LEFT
CAM_RGB = _gen3d.CAM_RGB
CAM_RIGHT = _gen3d.CAM_RIGHT
POINT_TO_CAM_LEFT = _gen3d.POINT_TO_CAM_LEFT
POINT_TO_CAM_RGB = _gen3d.POINT_TO_CAM_RGB
POINT_TO_CAM_RIGHT = _gen3d.POINT_TO_CAM_RIGHT
class Camera(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def DiscoverCameras(self, camInfoVector, timeout=1000):
        return _gen3d.Camera_DiscoverCameras(self, camInfoVector, timeout)

    def Open(self, cameraInfo, timeout=60000):
        return _gen3d.Camera_Open(self, cameraInfo, timeout)

    def Capture(self, cameraInfo, frameData):
        return _gen3d.Camera_Capture(self, cameraInfo, frameData)

    def RegisterErrorCodeHandler(self, errorCodeHandler):
        return _gen3d.Camera_RegisterErrorCodeHandler(self, errorCodeHandler)

    def RegisterFrameDataHandler(self, *args):
        return _gen3d.Camera_RegisterFrameDataHandler(self, *args)

    def CaptureDataAsync(self, cameraInfo):
        return _gen3d.Camera_CaptureDataAsync(self, cameraInfo)

    def SetCameraIP(self, cameraInfo, newIP):
        return _gen3d.Camera_SetCameraIP(self, cameraInfo, newIP)

    def SetCameraToDHCP(self, cameraInfo):
        return _gen3d.Camera_SetCameraToDHCP(self, cameraInfo)

    def CameraGetStatus(self, cameraInfo):
        return _gen3d.Camera_CameraGetStatus(self, cameraInfo)

    def SendMemsCommands(self, cameraInfo, strCommands):
        return _gen3d.Camera_SendMemsCommands(self, cameraInfo, strCommands)

    def SendAndRecvMemsCommands(self, cameraInfo, strCommands, strRecv):
        return _gen3d.Camera_SendAndRecvMemsCommands(self, cameraInfo, strCommands, strRecv)

    def CameraGetVersion(self, cameraInfo):
        return _gen3d.Camera_CameraGetVersion(self, cameraInfo)

    def CameraSetTriggerOutParam(self, cameraInfo, mode, cycleNumValue, cycleLenValue):
        return _gen3d.Camera_CameraSetTriggerOutParam(self, cameraInfo, mode, cycleNumValue, cycleLenValue)

    def CameraGetTriggerOutParam(self, cameraInfo, mode, cycleNumValue, cycleLenValue):
        return _gen3d.Camera_CameraGetTriggerOutParam(self, cameraInfo, mode, cycleNumValue, cycleLenValue)

    def CameraReboot(self, cameraInfo):
        return _gen3d.Camera_CameraReboot(self, cameraInfo)

    def AddParamGroup(self, cameraInfo, paramGroupName):
        return _gen3d.Camera_AddParamGroup(self, cameraInfo, paramGroupName)

    def GetParamGroups(self, cameraInfo, paramGroupNames):
        return _gen3d.Camera_GetParamGroups(self, cameraInfo, paramGroupNames)

    def DeleteParamGroup(self, cameraInfo, paramGroupName):
        return _gen3d.Camera_DeleteParamGroup(self, cameraInfo, paramGroupName)

    def ApplyParamGroup(self, cameraInfo, paramGroupName):
        return _gen3d.Camera_ApplyParamGroup(self, cameraInfo, paramGroupName)

    def ReconstructPoints(self, cameraInfo, leftPoints, rightPoints, points):
        return _gen3d.Camera_ReconstructPoints(self, cameraInfo, leftPoints, rightPoints, points)

    def GetAttributeTreeJson(self, cameraInfo, strAttributeTreeJson):
        return _gen3d.Camera_GetAttributeTreeJson(self, cameraInfo, strAttributeTreeJson)

    def GetNodeAttributeJson(self, cameraInfo, key, strNodeAttributeJson):
        return _gen3d.Camera_GetNodeAttributeJson(self, cameraInfo, key, strNodeAttributeJson)

    def SetValue(self, *args):
        return _gen3d.Camera_SetValue(self, *args)

    def GetValue(self, *args):
        return _gen3d.Camera_GetValue(self, *args)

    def Get3DCameraIntrinsic(self, cameraInfo, cameraPosition, cameraIntrinsic):
        return _gen3d.Camera_Get3DCameraIntrinsic(self, cameraInfo, cameraPosition, cameraIntrinsic)

    def Get3DCameraExtrinsic(self, cameraInfo, extrinsicType, cameraExtrinsic):
        return _gen3d.Camera_Get3DCameraExtrinsic(self, cameraInfo, extrinsicType, cameraExtrinsic)

    def GetDistortionCoefficients(self, cameraInfo, cameraPosition, distortionCoefficients):
        return _gen3d.Camera_GetDistortionCoefficients(self, cameraInfo, cameraPosition, distortionCoefficients)

    def Close(self, cameraInfo):
        return _gen3d.Camera_Close(self, cameraInfo)
    __swig_destroy__ = _gen3d.delete_Camera

# Register Camera in _gen3d:
_gen3d.Camera_swigregister(Camera)


def CreateCamera(type):
    return _gen3d.CreateCamera(type)

def DestoryCamera(cam):
    return _gen3d.DestoryCamera(cam)
ConfigFile = _gen3d.ConfigFile
CalibrationFile = _gen3d.CalibrationFile
LogFile = _gen3d.LogFile
FirmwareFile = _gen3d.FirmwareFile
ProjectorCalibrationFile = _gen3d.ProjectorCalibrationFile
MemsFirmwareFile = _gen3d.MemsFirmwareFile
SaveImagesToLocal = _gen3d.SaveImagesToLocal
Calibration = _gen3d.Calibration
Intrinsics = _gen3d.Intrinsics
Extrinsics = _gen3d.Extrinsics
Coefficient = _gen3d.Coefficient
class FrameDataEx(FrameData):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _gen3d.delete_FrameDataEx

    def __init__(self, *args):
        _gen3d.FrameDataEx_swiginit(self, _gen3d.new_FrameDataEx(*args))
    outputIR = property(_gen3d.FrameDataEx_outputIR_get, _gen3d.FrameDataEx_outputIR_set)
    outputIRSize = property(_gen3d.FrameDataEx_outputIRSize_get, _gen3d.FrameDataEx_outputIRSize_set)

# Register FrameDataEx in _gen3d:
_gen3d.FrameDataEx_swigregister(FrameDataEx)

class CameraInterfaceEx(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _gen3d.CameraInterfaceEx_swiginit(self, _gen3d.new_CameraInterfaceEx(*args))
    __swig_destroy__ = _gen3d.delete_CameraInterfaceEx

    def CaptureEx(self, cameraInfo, frameDataEx):
        return _gen3d.CameraInterfaceEx_CaptureEx(self, cameraInfo, frameDataEx)

    def CameraImportFile(self, cameraInfo, fileType, filePath, timeout=300000):
        return _gen3d.CameraInterfaceEx_CameraImportFile(self, cameraInfo, fileType, filePath, timeout)

    def CameraExportFile(self, cameraInfo, type, fileContent, timeout=300000):
        return _gen3d.CameraInterfaceEx_CameraExportFile(self, cameraInfo, type, fileContent, timeout)

    def RestoreParam(self, cameraInfo):
        return _gen3d.CameraInterfaceEx_RestoreParam(self, cameraInfo)

    def SaveParam(self, cameraInfo):
        return _gen3d.CameraInterfaceEx_SaveParam(self, cameraInfo)

    def GetConnectionStatus(self, cameraInfo):
        return _gen3d.CameraInterfaceEx_GetConnectionStatus(self, cameraInfo)

    def ExportParamGroup(self, cameraInfo, paramGroupName, destFilePath, timeout=15000):
        return _gen3d.CameraInterfaceEx_ExportParamGroup(self, cameraInfo, paramGroupName, destFilePath, timeout)

    def SetDebugMode(self, cameraInfo, debugMode):
        return _gen3d.CameraInterfaceEx_SetDebugMode(self, cameraInfo, debugMode)

    def CameraGetCalibrationMatrix(self, cameraInfo, type, matrix):
        return _gen3d.CameraInterfaceEx_CameraGetCalibrationMatrix(self, cameraInfo, type, matrix)

    def SetContinuousExposure(self, cameraInfo, continuousExposureList):
        return _gen3d.CameraInterfaceEx_SetContinuousExposure(self, cameraInfo, continuousExposureList)

    def SetInternalValue(self, cameraInfo, key, value):
        return _gen3d.CameraInterfaceEx_SetInternalValue(self, cameraInfo, key, value)

# Register CameraInterfaceEx in _gen3d:
_gen3d.CameraInterfaceEx_swigregister(CameraInterfaceEx)


cvar = _gen3d.cvar
mapMemsStripesType = cvar.mapMemsStripesType

